# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  csrf_protection: true

  # Configuration simplifiée des sessions
  session:
    cookie_secure: false # Permet HTTP en local même en mode prod
    cookie_samesite: lax
    cookie_lifetime: 3600 # 1 heure

  #esi: true
  #fragments: true

when@test:
  framework:
    test: true
